version: '3'

services:

  nginx:
    container_name: tg_nginx
    image: nginx:1.19-alpine
    restart: always
    depends_on:
      - backend
    volumes:
      - ./static:/static
      - ./media:/media
      - ./nginx.conf.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - "9999:80"

  redis:
    container_name: tg_redis
    image: redis:6.0.6-alpine
    restart: always

  postgres:
    container_name: tg_postgres
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    container_name: pg_backend
    image: khvostenko/tgclient:latest
    restart: always
    command: bash -c "
      sleep 24
      && python manage.py migrate
      && gunicorn TG_client.wsgi:application -t 300 -w 2 -b 0.0.0.0:8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - postgres
      - redis

  celery:
    container_name: tg_celery
    image: khvostenko/tgclient:latest
    restart: always
    command: bash -c "
      sleep 12
      && celery -A TG_client worker -n w_1@%n --concurrency=40 -l info
      && celery -A TG_client worker -n w_2@%n --concurrency=40 -l info
      && celery -A TG_client worker -n w_3@%n --concurrency=40 -l info
      && celery -A TG_client worker -n w_4@%n --concurrency=40 -l info
      && celery -A TG_client worker -n w_5@%n --concurrency=40 -l info
      && celery -A TG_client worker -n w_6@%n --concurrency=40 -l info
      && celery -A TG_client worker -n w_7@%n --concurrency=40 -l info
      && celery -A TG_client worker -n w_8@%n --concurrency=40 -l info
      && celery -A TG_client worker -n w_9@%n --concurrency=40 -l info
      && celery -A TG_client worker -n w_10@%n --concurrency=40 -l info"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - postgres
      - redis

  celery-beat:
    container_name: tg_celery_beat
    image: khvostenko/tgclient:latest
    restart: always
    command: bash -c "
      sleep 36
      && celery -A TG_client.celery beat -l info -S django"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - postgres
      - redis
