# Generated by Django 4.1.2 on 2025-08-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("params", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="user_id",
        ),
        migrations.AddField(
            model_name="log",
            name="stream",
            field=models.IntegerField(default=0, verbose_name="Stream"),
        ),
    ]
