# Generated by Django 5.1.3 on 2025-09-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "api_id",
                    models.CharField(default="", max_length=64, verbose_name="ApiId"),
                ),
                (
                    "api_hash",
                    models.CharField(default="", max_length=64, verbose_name="ApiHash"),
                ),
                (
                    "tg_id",
                    models.CharField(default="", max_length=64, verbose_name="TG ID"),
                ),
                (
                    "phone",
                    models.CharField(default="", max_length=16, verbose_name="Phone"),
                ),
                (
                    "password",
                    models.CharField(
                        default="", max_length=32, verbose_name="Cloud Password"
                    ),
                ),
                (
                    "proxy",
                    models.CharField(default="", max_length=128, verbose_name="Proxy"),
                ),
                (
                    "device_model",
                    models.CharField(default="", max_length=256, verbose_name="Device"),
                ),
                (
                    "system_version",
                    models.CharField(
                        default="", max_length=32, verbose_name="System ver"
                    ),
                ),
                (
                    "app_version",
                    models.CharField(default="", max_length=4, verbose_name="App ver"),
                ),
                (
                    "lang_code",
                    models.CharField(
                        default="", max_length=4, verbose_name="Lang code"
                    ),
                ),
                (
                    "system_lang_code",
                    models.CharField(
                        default="", max_length=4, verbose_name="System lang"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
            ],
            options={
                "verbose_name": "TG-user",
                "verbose_name_plural": "TG-users",
                "ordering": ["pk"],
            },
        ),
    ]
