# Generated by Django 5.1.3 on 2025-11-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="session",
            field=models.TextField(
                blank=True, default="", verbose_name="Telethon Session"
            ),
        ),
    ]
