# Generated by Django 4.1.2 on 2025-08-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="cloud_password",
        ),
        migrations.AlterField(
            model_name="confirmation",
            name="code",
            field=models.CharField(default="", max_length=16, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="confirmation",
            name="user",
            field=models.IntegerField(default=0, unique=True, verbose_name="User"),
        ),
        migrations.AlterField(
            model_name="user",
            name="app_version",
            field=models.CharField(default="", max_length=4, verbose_name="App ver"),
        ),
        migrations.AlterField(
            model_name="user",
            name="device_model",
            field=models.CharField(default="", max_length=256, verbose_name="Device"),
        ),
        migrations.AlterField(
            model_name="user",
            name="lang_code",
            field=models.CharField(default="", max_length=4, verbose_name="Lang code"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="", max_length=32, verbose_name="Cloud Password"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="system_lang_code",
            field=models.CharField(
                default="", max_length=4, verbose_name="System lang"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="system_version",
            field=models.CharField(
                default="", max_length=32, verbose_name="System ver"
            ),
        ),
    ]
