# Generated by Django 5.1.3 on 2025-09-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_remove_user_cloud_password_alter_confirmation_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["pk"],
                "verbose_name": "TG-user",
                "verbose_name_plural": "TG-users",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="tg_id",
            field=models.CharField(default="", max_length=64, verbose_name="TG ID"),
        ),
    ]
