# Generated by Django 5.1.3 on 2025-09-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TGgroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="Name"),
                ),
                (
                    "chat_id",
                    models.CharField(default="", max_length=64, verbose_name="Chat ID"),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=256, verbose_name="Title"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
            ],
            options={
                "verbose_name": "TGgroup",
                "verbose_name_plural": "TGgroups",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="Task"),
                ),
                ("period", models.IntegerField(default=0, verbose_name="Period")),
                ("limit", models.IntegerField(default=1, verbose_name="Limit")),
                (
                    "action",
                    models.CharField(
                        choices=[("LISTEN", "Listen"), ("PARSE", "Parse messages")],
                        default="LISTEN",
                        max_length=16,
                        verbose_name="Action",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CHECK", "Check"),
                            ("READY", "Ready"),
                            ("RUN", "Run"),
                            ("STOP", "Stop"),
                            ("FINISH", "Finish"),
                            ("WAIT", "Wait"),
                        ],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "errors",
                    models.IntegerField(default=0, verbose_name="Errors counter"),
                ),
                (
                    "found",
                    models.IntegerField(default=0, verbose_name="Messages counter"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="accounts.user",
                        verbose_name="Admin",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="tasks",
                        to="tasks.tggroup",
                        verbose_name="To parse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["pk"],
            },
        ),
    ]
