# Generated by Django 5.1.3 on 2025-09-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tggroup",
            name="chat_link",
        ),
        migrations.AddField(
            model_name="tggroup",
            name="title",
            field=models.CharField(default="", max_length=256, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="tggroup",
            name="chat_id",
            field=models.CharField(default="", max_length=64, verbose_name="Chat ID"),
        ),
    ]
