# Generated by Django 5.1.3 on 2025-10-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="url",
            field=models.CharField(
                default="", max_length=2048, verbose_name="Endpoint"
            ),
        ),
    ]
